"""Register the custom trainers with nnU-Net.

nnU-Net v2 discovers trainers only under
``nnunetv2/training/nnUNetTrainer/``. We therefore drop a tiny shim module there
that imports our trainers from ``segment.fine.trainer`` so ``-tr
nnUNetTrainerTransUNetCC`` resolves. The shim is idempotent and can be removed
with :func:`uninstall_trainer_shim`.
"""

from __future__ import annotations

from pathlib import Path

_SHIM_NAME = "segment_trainers.py"
_SHIM_BODY = '''# Auto-generated by `segment install-trainers`. Re-exports custom trainers
# so nnU-Net's recursive_find_python_class can discover them.
from segment.fine.trainer import (  # noqa: F401
    nnUNetTrainerUnfavorSeg,
    nnUNetTrainerTransUNet,
    nnUNetTrainerTransUNetCC,
)
'''


def _trainer_dir() -> Path:
    import nnunetv2.training.nnUNetTrainer as pkg

    return Path(pkg.__file__).resolve().parent


def install_trainer_shim() -> Path:
    target = _trainer_dir() / _SHIM_NAME
    target.write_text(_SHIM_BODY, encoding="utf-8")
    return target


def uninstall_trainer_shim() -> None:
    target = _trainer_dir() / _SHIM_NAME
    if target.exists():
        target.unlink()
